Repository modern-agile-team/moae-blog-server, pull requests merged in 2022-10, with the labels that each got.

#17 [Feat: [#13] accesstoken, refreshtoken 처리 로직 추가
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20220928122436_init/migration.sql
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/decorator/current-user.decorator.ts
  src/auth/dto/current-user.dto.ts
  src/common/interfaces/jwt-payload.interface.ts
  src/common/strategy/google.strategy.ts
  src/common/strategy/refresh-token.strategy.ts
  src/common/strategy/token.strategy.ts
  src/config/jwt/jwt.config.ts
  src/config/swagger/swagger.ts
  src/prisma/prisma.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: ✅ Done

#21 Fix: [#20] 도커, 레디스 연결 이슈 해결
  docker-compose.yaml
  src/app.module.ts
  src/auth/auth.module.ts
  src/config/redis/redis.config.ts
Labels: ✅ Done

#24 Feat: [#13] jwt 검증 로직 추가
  docker-compose.yaml
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/boards/boards.controller.ts
  src/boards/boards.module.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/select-board.dto.ts
  src/boards/repository/boards.repository.ts
  src/cache/cache.config.ts
  src/cache/cache.module.ts
  src/cache/cache.service.spec.ts
  src/cache/cache.service.ts
  src/common/decorators/user.decorator.ts
  src/config/redis/redis.config.ts
Labels: 🏃🏻 In Progress

#28 Feat, Refactor: board entity 추가
  src/boards/boards.entity.ts
  src/boards/boards.module.ts
  src/boards/repository/boards.repository.ts
  src/config/swagger/swagger.ts
  src/prisma/prisma.service.ts
Labels: 🏃🏻 In Progress

#33 Refactor: board refactor
  src/boards/boards.controller.ts
  src/boards/boards.entity.ts
  src/boards/boards.service.ts
  src/boards/dto/select-board.dto.ts
  src/boards/interfaces/delete.interface.ts
  src/boards/interfaces/update.interface.ts
  src/boards/repository/boards.repository.ts
Labels: ✅ Done

#34 Feature, Refactor: [#22, #31] Comment API 리팩토링 및 Prisma Seed 추가
  package-lock.json
  package.json
  prisma/seed.ts
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/entity/comment.entity.ts
  src/comments/repository/comments.repository.ts
Labels: 🛠 NPM

#35 Refactor: common type 추가 및 board 내용 변경
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/interfaces/delete.interface.ts
  src/boards/interfaces/update.interface.ts
  src/boards/repository/boards.repository.ts
  src/common/interfaces/index.interface.ts
Labels: ✅ Done

#37 Docs: board swagger 추가 & 관련 내용 refactoring
  src/app.module.ts
  src/board/board.controller.spec.ts
  src/board/board.controller.ts
  src/board/board.entity.ts
  src/board/board.module.ts
  src/board/board.service.spec.ts
  src/board/board.service.ts
  src/board/dto/create-board.dto.ts
  src/board/dto/select-board.dto.ts
  src/board/dto/update-board.dto.ts
  src/board/repository/board.repository.ts
  src/boards/boards.module.ts
  src/common/decorators/compose-swagger.decorator.ts
Labels: 🏃🏻 In Progress

#41 Build: docker compose redis 관련 내용 변경
  docker-compose.yaml
Labels: 🏃🏻 In Progress

#42 CI/CD: prod 도커 동작 확인
  docker-compose.yaml
Labels: 🏃🏻 In Progress
