Repository modern-agile-team/moae-blog-server, pull requests merged in 2023-01, with the labels that each got.

#48 Feature & Setting: 좋아요 기능 추가 및 도커 파일 변경
  dockerfile
  package-lock.json
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.ts
  src/board/board.controller.ts
  src/common/decorators/compose-swagger.decorator.ts
  src/like/dto/get-count.dto.ts
  src/like/dto/request-like.dto.ts
  src/like/like.controller.spec.ts
  src/like/like.controller.ts
  src/like/like.entity.ts
  src/like/like.module.ts
  src/like/like.service.spec.ts
  src/like/like.service.ts
  src/like/repository/likes.repository.ts
  src/likes/likes.controller.ts
  src/likes/likes.module.ts
  src/likes/likes.service.ts
  src/likes/repository/likes.repository.ts
Labels: 🏃🏻 In Progress

#49 Feature & Refcator: redis password and board api
  dockerfile
  dump.rdb
  package-lock.json
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/board/board.controller.ts
  src/board/board.module.ts
  src/board/board.service.ts
  src/board/dto/create-board.dto.ts
  src/cache/cache.config.ts
  src/category-on-board/category-on-board.controller.ts
  src/category-on-board/category-on-board.entity.ts
  src/category-on-board/category-on-board.module.ts
  src/category-on-board/category-on-board.service.ts
  src/category-on-board/repository/category-on-board.repository.ts
  src/category/category.controller.ts
  src/category/category.entity.ts
  src/category/category.module.ts
  src/category/category.service.ts
  src/category/repository/category.repository.ts
  src/common/decorators/compose-swagger.decorator.ts
  src/like/dto/get-count.dto.ts
  src/like/dto/request-like.dto.ts
  src/like/like.controller.spec.ts
  src/like/like.controller.ts
  src/like/like.entity.ts
  src/like/like.module.ts
  src/like/like.service.spec.ts
  src/like/like.service.ts
  src/like/repository/likes.repository.ts
  src/likes/likes.controller.ts
  src/likes/likes.module.ts
  src/likes/likes.service.ts
  src/likes/repository/likes.repository.ts
Labels: 🐞 Bug

#55 Feature: [#13, #43] 구글 oauth 제거 및 auth 기능 강화
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/dto/current-user.dto.ts
  src/auth/dto/token.dto.ts
  src/board/board.controller.ts
  src/common/decorators/compose-swagger.decorator.ts
  src/common/strategy/google.strategy.ts
  src/like/like.controller.ts
  src/users/users.service.ts
Labels: ✅ Done
